name: keezy
description: "Proteção inteligente para suas senhas e dados"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^16.1.0
  shared_preferences: ^2.5.3
  provider: ^6.1.5
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  intl: ^0.20.2
  font_awesome_flutter: ^10.9.0
  equatable: ^2.0.7
  animations: ^2.0.11
  local_auth: ^3.0.0
  encrypt: ^5.0.3
  form_field_validator: ^1.1.0
  flutter_native_splash: ^2.4.6
  uuid: ^4.5.1
  flutter_launcher_icons: ^0.14.4
  path_provider: ^2.1.5
  share_plus: ^12.0.1
  modal_bottom_sheet: ^3.0.0
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.0
  file_picker: ^10.2.4
  csv: ^6.0.0
  installed_apps: ^2.0.0

  introduction_screen: ^4.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  hive_generator:

flutter:

  uses-material-design: true

  assets:
    - assets/images/

parts:
  uet-lms:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
    build-packages:
      - libsecret-1-dev
      - libjsoncpp-dev
    stage-packages:
      - libsecret-1-0
      - libjsoncpp-dev