name: keezy
description: "Proteção inteligente para suas senhas e dados"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
    
  go_router: ^15.1.1
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  intl: ^0.20.2
  font_awesome_flutter: ^10.7.0
  equatable: ^2.0.5
  animations: ^2.0.11
  local_auth: ^2.3.0
  encrypt: ^5.0.3
  form_field_validator: ^1.1.0
  flutter_native_splash: ^2.4.3
  uuid: ^4.5.1
  flutter_launcher_icons: ^0.14.3
  path_provider: ^2.1.5
  share_plus: ^11.0.0
  modal_bottom_sheet: ^3.0.0
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.16
  file_picker: ^10.1.2
  csv: ^6.0.0
  installed_apps: ^1.6.0


  #Creating app Introduction screens
  introduction_screen: ^3.1.14
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1


flutter:
  uses-material-design: true


  assets:
    - assets/images/

parts:
  uet-lms:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
    build-packages:
      - libsecret-1-dev
      - libjsoncpp-dev
    stage-packages:
      - libsecret-1-0
      - libjsoncpp-dev
